export const queryKeys = {
  projects: ['projects'] as const,
  project: (projectId: string) => ['projects', projectId] as const,
  overview: (projectId: string) => ['projects', projectId, 'overview'] as const,
  clientView: (projectId: string) => ['projects', projectId, 'client-view'] as const,
  leads: (projectId: string) => ['projects', projectId, 'leads'] as const,
  lead: (leadId: string) => ['leads', leadId] as const,
  tasks: (projectId: string) => ['projects', projectId, 'tasks'] as const,
  campaigns: (projectId: string) => ['projects', projectId, 'campaigns'] as const,
  campaign: (campaignId: string) => ['campaigns', campaignId] as const,
  calendar: (projectId: string) => ['projects', projectId, 'calendar'] as const,
  approvals: (projectId: string) => ['projects', projectId, 'approvals'] as const,
  report: (projectId: string) => ['projects', projectId, 'report'] as const,
  projectTeam: (projectId: string) => ['projects', projectId, 'team'] as const,
  agencyTeam: ['team'] as const,
  teamMember: (memberId: string) => ['team', memberId] as const,
  settings: ['settings'] as const,
  inbox: ['inbox'] as const,
};
